
import LoginForm from '../login'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Nested Dashboard',
    description: 'Generated by create next app',
  }

export default function mainLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <>
        <nav>
          <LoginForm />
        </nav>
        <main>
          {children}
        </main>
      </>
    )
  }